apiVersion: v1
kind: Service
metadata:
  name: memcached
  namespace: flux
spec:
  clusterIP: 10.96.253.142
  clusterIPs:
  - 10.96.253.142
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: memcached
    port: 11211
  selector:
    name: memcached
